import { type NextPage } from 'next';
import Head from 'next/head';
import { useSession } from 'next-auth/react';
import { trpc } from '../utils/trpc';
import CreatePost from '../components/CreatePost';
import PostsList from '../components/PostsList';
import Navbar from '../components/Navbar';

const Home: NextPage = () => {
  const { data: session } = useSession();
  const { data: posts, refetch } = trpc.post.getPosts.useQuery(
    undefined, // no input
    { enabled: session?.user !== undefined }
  );

  return (
    <>
      <Head>
        <title>Bird App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="m-6 flex flex-col items-center justify-center md:flex-row md:items-start">
        <CreatePost refetch={refetch} />
        <PostsList posts={posts} refetch={refetch} />
      </main>
    </>
  );
};

export default Home;
